DROP TABLE ENLINEA CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTE CASCADE CONSTRAINTS;
DROP TABLE VENTAMENU CASCADE CONSTRAINTS;
DROP TABLE VENTAPLATO CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;
DROP TABLE PLATO CASCADE CONSTRAINTS;
DROP TABLE PLATORESTAURANTE CASCADE CONSTRAINTS;
DROP TABLE PREFERENCIACOMIDA CASCADE CONSTRAINTS;
DROP TABLE PREFERENCIAPRECIO CASCADE CONSTRAINTS;
DROP TABLE PREFERENCIAZONA CASCADE CONSTRAINTS;
DROP TABLE RESTAURANTE CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE VENTA CASCADE CONSTRAINTS;
DROP TABLE VENTAANONIMA CASCADE CONSTRAINTS;
DROP TABLE ZONA CASCADE CONSTRAINTS;


CREATE TABLE ENLINEA 
(
  IDUSUARIO NUMBER NOT NULL,
  CONSTRAINT ENLINEA_PK PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE INGREDIENTE
(
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  IDINGREDIENTE NUMBER NOT NULL,
  DESCRIPCIONESPAÑOL VARCHAR2(255 BYTE) NOT NULL,
  TRADUCCIONINGLES VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT INGREDIENTE_PK PRIMARY KEY (IDINGREDIENTE)
);

CREATE TABLE MENU
(
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  PRECIO NUMBER NOT NULL,
  IDMENU NUMBER NOT NULL,
  IDRESTAURANTE NUMBER NOT NULL,
  IDPOSTRE NUMBER,
  IDPLATOFUERTE NUMBER,
  IDENTRADA NUMBER,
  IDBEBIDA NUMBER,
  IDACOMPAÑAMIENTO NUMBER,
  FECHAINI DATE NOT NULL,
  FECHAFIN DATE NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  CONSTRAINT MENU_PK PRIMARY KEY (IDMENU)
);


CREATE TABLE PLATO
(
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  IDPLATO NUMBER NOT NULL,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  TIEMPO NUMBER NOT NULL,
  DESCRIPCIONESPAÑOL VARCHAR2(255 BYTE) NOT NULL,
  TRADUCCIONINGLES VARCHAR2(255 BYTE) NOT NULL,
  GENERO VARCHAR2(255 BYTE),
  CONSTRAINT PLATO_PK PRIMARY KEY (IDPLATO)
);

CREATE TABLE PLATORESTAURANTE
(
  PRECIOVENTA NUMBER NOT NULL,
  PRECIOPRODUCCION NUMBER NOT NULL,
  IDPLATO NUMBER NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  IDRESTAURANTE NUMBER NOT NULL,
  FECHAINI DATE NOT NULL,
  FECHAFIN DATE NOT NULL,
  CONSTRAINT PLATORESTAURANTE_PK PRIMARY KEY (IDPLATO, IDRESTAURANTE)
);


CREATE TABLE PREFERENCIACOMIDA
(
  IDCLIENTE NUMBER NOT NULL,
  PREFERENCIACOMIDA VARCHAR2(255 BYTE) NOT NULL,
  IDCOMIDA NUMBER NOT NULL,
  CONSTRAINT PREFERENCIACOMIDA_PK PRIMARY KEY (IDCOMIDA)
);


CREATE TABLE PREFERENCIAPRECIO
(
  IDCLIENTE NUMBER NOT NULL,
  PREFERENCIAPRECIO NUMBER NOT NULL,
  IDPRECIO NUMBER NOT NULL,
  CONSTRAINT PREFERENCIAPRECIO_PK PRIMARY KEY (IDPRECIO)
);

CREATE TABLE PREFERENCIAZONA
(
  IDCLIENTE NUMBER NOT NULL,
  PREFERENCIAZONA NUMBER NOT NULL,
  IDZONA NUMBER NOT NULL,
  CONSTRAINT PREFERENCIAZONA_PK PRIMARY KEY (IDZONA)
);

CREATE TABLE RESTAURANTE
(
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  ESPECIALIDAD VARCHAR2(255 BYTE) NOT NULL,
  IDRESTAURANTE NUMBER NOT NULL,
  PAGINAWEB VARCHAR2(255 BYTE),
  IDZONA NUMBER NOT NULL,
  CONSTRAINT RESTAURANTE_PK PRIMARY KEY (IDRESTAURANTE)
);


CREATE TABLE USUARIO
(
  IDENTIFICACION NUMBER NOT NULL,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  ROL VARCHAR2(255 BYTE) NOT NULL,
  CORREO VARCHAR2(255 BYTE),
  RESTAURANTEID NUMBER,
  CONSTRAINT USUARIO_PK PRIMARY KEY (IDENTIFICACION)
);


CREATE TABLE VENTA
(
  IDVENTA NUMBER NOT NULL,
  IDCLIENTE NUMBER NOT NULL,
  FECHA DATE NOT NULL,
  HORA NUMBER NOT NULL,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT VENTA_PK PRIMARY KEY (IDVENTA)
);


CREATE TABLE VENTAANONIMA
(
  CEDULA NUMBER NOT NULL,
  PRECIO NUMBER NOT NULL,
  IDVENTAA NUMBER NOT NULL,
  FECHA DATE NOT NULL,
  HORA NUMBER NOT NULL,
  IDMENU NUMBER,
  IDPLATO NUMBER,
  CANTIDAD NUMBER NOT NULL,
  IDRESTAURANTE NUMBER NOT NULL,
  CONSTRAINT VENTAANONIMA_PK PRIMARY KEY (IDVENTAA)
);


CREATE TABLE VENTAMENU
(
  IDVENTA NUMBER NOT NULL,
  IDMENU NUMBER NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  IDRESTAURANTE NUMBER NOT NULL,
  PRECIO NUMBER NOT NULL,
  CONSTRAINT VENTAMENU_PK PRIMARY KEY (IDVENTA)
);


CREATE TABLE VENTAPLATO
(
  IDVENTA NUMBER NOT NULL,
  IDPLATO NUMBER NOT NULL,
  CANTIDAD NUMBER NOT NULL,
  IDRESTAURANTE NUMBER NOT NULL,
  PRECIO NUMBER NOT NULL,
  CONSTRAINT VENTAPLATO_PK PRIMARY KEY (IDVENTA)
);


CREATE TABLE ZONA
(
  ESPECIALIDAD VARCHAR2(255 BYTE) NOT NULL,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  CAPACIDAD NUMBER NOT NULL,
  APTO VARCHAR2(255 BYTE) NOT NULL,
  IDZONA NUMBER NOT NULL,
  AMBIENTE VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT ZONA_PK PRIMARY KEY (IDZONA)
);


ALTER TABLE ENLINEA ADD CONSTRAINT ENLINEA_FK1 FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDENTIFICACION);

ALTER TABLE MENU ADD CONSTRAINT MENU_FK1 FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE(IDRESTAURANTE);
ALTER TABLE MENU ADD CONSTRAINT MENU_FK2 FOREIGN KEY (IDPOSTRE) REFERENCES PLATO(IDPLATO);
ALTER TABLE MENU ADD CONSTRAINT MENU_FK3 FOREIGN KEY (IDPLATOFUERTE) REFERENCES PLATO(IDPLATO);
ALTER TABLE MENU ADD CONSTRAINT MENU_FK4 FOREIGN KEY (IDENTRADA) REFERENCES PLATO(IDPLATO);
ALTER TABLE MENU ADD CONSTRAINT MENU_FK5 FOREIGN KEY (IDBEBIDA) REFERENCES PLATO(IDPLATO);
ALTER TABLE MENU ADD CONSTRAINT MENU_FK6 FOREIGN KEY (IDACOMPAÑAMIENTO) REFERENCES PLATO(IDPLATO);

ALTER TABLE PLATORESTAURANTE ADD CONSTRAINT PLATORESTAURANTE_FK1 FOREIGN KEY (IDPLATO) REFERENCES PLATO(IDPLATO);
ALTER TABLE PLATORESTAURANTE ADD CONSTRAINT PLATORESTAURANTE_FK2 FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE(IDRESTAURANTE);

ALTER TABLE PREFERENCIACOMIDA ADD CONSTRAINT PREFERENCIACOMIDA_FK1 FOREIGN KEY (IDCLIENTE) REFERENCES USUARIO(IDENTIFICACION);

ALTER TABLE PREFERENCIAPRECIO ADD CONSTRAINT PREFERENCIAPRECIO_FK1 FOREIGN KEY (IDCLIENTE) REFERENCES USUARIO(IDENTIFICACION);

ALTER TABLE PREFERENCIAZONA ADD CONSTRAINT PREFERENCIAZONA_FK1 FOREIGN KEY (IDCLIENTE) REFERENCES USUARIO(IDENTIFICACION);
 
ALTER TABLE RESTAURANTE ADD CONSTRAINT RESTAURANTE_FK1 FOREIGN KEY (IDZONA) REFERENCES ZONA(IDZONA);

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FK1 FOREIGN KEY (RESTAURANTEID) REFERENCES RESTAURANTE(IDRESTAURANTE);

ALTER TABLE VENTA ADD CONSTRAINT VENTA_FK1 FOREIGN KEY (IDCLIENTE) REFERENCES USUARIO(IDENTIFICACION);
  
ALTER TABLE VENTAMENU ADD CONSTRAINT VENTAMENU_FK1 FOREIGN KEY (IDMENU) REFERENCES MENU(IDMENU);
ALTER TABLE VENTAMENU ADD CONSTRAINT VENTAMENU_FK2 FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA);
ALTER TABLE VENTAMENU ADD CONSTRAINT VENTAMENU_FK3 FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE(IDRESTAURANTE);

ALTER TABLE VENTAPLATO ADD CONSTRAINT VENTAPLATO_FK1 FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE(IDRESTAURANTE);
ALTER TABLE VENTAPLATO ADD CONSTRAINT VENTAPLATO_FK2 FOREIGN KEY (IDVENTA) REFERENCES VENTA(IDVENTA);
ALTER TABLE VENTAPLATO ADD CONSTRAINT VENTAPLATO_FK3 FOREIGN KEY (IDPLATO) REFERENCES PLATO(IDPLATO);

  
INSERT INTO ZONA (ESPECIALIDAD,TIPO,CAPACIDAD,APTO,IDZONA,AMBIENTE) VALUES ('china','cerrado',150,'si',100,'comodo');
INSERT INTO ZONA (ESPECIALIDAD,TIPO,CAPACIDAD,APTO,IDZONA,AMBIENTE) VALUES ('arroz','cerrado',50,'no',191,'poco comodo');


INSERT INTO RESTAURANTE(NOMBRE,ESPECIALIDAD,IDRESTAURANTE,PAGINAWEB,IDZONA) VALUES ('crepes','crepes',10,'crepes.com',100);

INSERT INTO USUARIO (IDENTIFICACION,NOMBRE,ROL,CORREO,RESTAURANTEID) VALUES (1,'david andres','cliente','david@gmail.com',NULL);
INSERT INTO USUARIO (IDENTIFICACION,NOMBRE,ROL,CORREO,RESTAURANTEID) VALUES (2,'carlos','administrador','carlos@gmail.com',NULL);
INSERT INTO USUARIO (IDENTIFICACION,NOMBRE,ROL,CORREO,RESTAURANTEID) VALUES (3,'felipe','representante','felipe@gmail.com',10);

INSERT INTO PREFERENCIACOMIDA (IDCLIENTE,PREFERENCIACOMIDA,IDCOMIDA) VALUES (1,'pasta',1);
INSERT INTO PREFERENCIAPRECIO (IDCLIENTE,PREFERENCIAPRECIO,IDPRECIO) VALUES (1,999,2);
INSERT INTO PREFERENCIAZONA (IDCLIENTE,PREFERENCIAZONA,IDZONA) VALUES (1,100,3);

INSERT INTO PREFERENCIACOMIDA (IDCLIENTE,PREFERENCIACOMIDA,IDCOMIDA) VALUES (1,'carne',100);
INSERT INTO PREFERENCIAPRECIO (IDCLIENTE,PREFERENCIAPRECIO,IDPRECIO) VALUES (1,258,200);
INSERT INTO PREFERENCIAZONA (IDCLIENTE,PREFERENCIAZONA,IDZONA) VALUES (1,191,300);

INSERT INTO PLATO (NOMBRE,IDPLATO,TIPO,TIEMPO,DESCRIPCIONESPAÑOL,TRADUCCIONINGLES,GENERO) VALUES ('pollo con miel',50,'platoFuerto',20,'pollo rico','tasty chicken','carne');

INSERT INTO PLATORESTAURANTE (PRECIOVENTA,PRECIOPRODUCCION,IDPLATO,CANTIDAD,IDRESTAURANTE,FECHAINI,FECHAFIN) VALUES (10000,5000,50,1000,10,DATE '2015-10-10',DATE '2018-11-10');

INSERT INTO MENU (NOMBRE,PRECIO,IDMENU,IDRESTAURANTE,IDPOSTRE,IDPLATOFUERTE,IDENTRADA,IDBEBIDA,IDACOMPAÑAMIENTO,FECHAINI,FECHAFIN,CANTIDAD) VALUES ('queso',10000,200,10,NULL,50,NULL,NULL,NULL,DATE '2015-10-10',DATE '2018-11-10',2000);

INSERT INTO INGREDIENTE (NOMBRE,IDINGREDIENTE,DESCRIPCIONESPAÑOL,TRADUCCIONINGLES) VALUES ('azucar',20,'buena azucar','nice sugar');

INSERT INTO ENLINEA (IDUSUARIO) VALUES (1);

INSERT INTO VENTA (IDVENTA,IDCLIENTE,FECHA,HORA,TIPO) VALUES (1,1,DATE '2017-10-10',22,'plato');
INSERT INTO VENTA (IDVENTA,IDCLIENTE,FECHA,HORA,TIPO) VALUES (5,1,DATE '2017-10-10',22,'menu');

INSERT INTO VENTAMENU (IDVENTA,IDMENU,CANTIDAD,IDRESTAURANTE,PRECIO) VALUES (5,200,1,10,50000);
INSERT INTO VENTAPLATO (IDVENTA,IDPLATO,CANTIDAD,IDRESTAURANTE,PRECIO) VALUES (1,50,1,10,20000);

INSERT INTO VENTAANONIMA (CEDULA,PRECIO,IDVENTAA,FECHA,HORA,IDMENU,IDPLATO,CANTIDAD,IDRESTAURANTE) VALUES (10205498,5000,3,DATE '2017-01-01',22,NULL,50,1,10);

COMMIT;


